name: Main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.2
      - name: Install
        run: just install
      - name: Test
        run: just test
      - name: Build
        run: just build
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: bin/
